# Generated by Django 6.1.1 on 2026-10-03 20:37

import django.contrib.postgres.fields
from django.contrib.postgres.operations import BtreeGistExtension
import django.db.models.expressions
import lety.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # Potřeba pro pravidlo „letadlo bez překryvu“ (rovnost + překryv intervalů).
        BtreeGistExtension(),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kdy', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('akce', models.CharField(max_length=30)),
                ('objekt', models.CharField(max_length=30)),
                ('objekt_id', models.BigIntegerField()),
                ('zmeny', models.JSONField(blank=True, default=dict)),
                ('duvod', models.CharField(blank=True, max_length=30, verbose_name='důvod')),
                ('poznamka', models.CharField(blank=True, max_length=300, verbose_name='poznámka')),
            ],
            options={
                'verbose_name': 'záznam auditního logu',
                'verbose_name_plural': 'auditní log',
                'ordering': ['-kdy', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Let',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stav', models.CharField(choices=[('pripraven', 'Připraven'), ('ve_vzduchu', 'Ve vzduchu'), ('ukoncen', 'Ukončen'), ('zrusen', 'Zrušen')], default='pripraven', max_length=12)),
                ('ucel', models.CharField(choices=[('normalni', 'Normální'), ('vycvik', 'Výcvik'), ('vycvik_solo', 'Výcvik sólo'), ('prezkouseni', 'Přezkoušení'), ('vlek', 'Vlek')], max_length=12, verbose_name='účel')),
                ('zpusob_vzletu', models.CharField(choices=[('vlastni', 'Vlastní'), ('navijak', 'Naviják'), ('vlek', 'Vlek'), ('autostart', 'Autostart')], default='vlastni', max_length=10, verbose_name='způsob vzletu')),
                ('cas_vzletu', models.DateTimeField(blank=True, null=True, verbose_name='vzlet (UTC)')),
                ('cas_pristani', models.DateTimeField(blank=True, null=True, verbose_name='přistání (UTC)')),
                ('doba_min', models.GeneratedField(db_persist=True, expression=lety.models.DobaLetuMin(django.db.models.expressions.CombinedExpression(models.F('cas_pristani'), '-', models.F('cas_vzletu'))), output_field=models.IntegerField(), verbose_name='doba [min]')),
                ('kratky_let', models.CharField(blank=True, choices=[('start_bez_doby', 'Start se počítá, doba 0 min'), ('normalni', 'Normální let')], help_text='Jen u letů do 1 minuty.', max_length=16, verbose_name='krátký let')),
                ('pocet_tg', models.PositiveSmallIntegerField(default=0, verbose_name='touch-and-go')),
                ('pocet_hostu', models.PositiveSmallIntegerField(default=0, help_text='Osoby mimo klub (jen počet).', verbose_name='hosté')),
                ('plati_aeroklub', models.BooleanField(default=False, verbose_name='platí aeroklub')),
                ('soukrome', models.BooleanField(default=False, help_text='Kopie příznaku letadla v okamžiku letu.', verbose_name='soukromé letadlo')),
                ('duvod_zruseni', models.CharField(blank=True, choices=[('technicka_zavada', 'Technická závada'), ('pocasi', 'Počasí'), ('omyl', 'Založeno omylem'), ('preruseny_vzlet', 'Přerušený vzlet'), ('jine', 'Jiné')], max_length=20, verbose_name='důvod zrušení')),
                ('opraveno_po_uzaverce', models.BooleanField(default=False, verbose_name='opraveno po uzávěrce')),
                ('zalozeno', models.DateTimeField(auto_now_add=True, verbose_name='založeno')),
                ('zmeneno', models.DateTimeField(auto_now=True, verbose_name='změněno')),
                ('verze', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'let',
                'verbose_name_plural': 'lety',
                'ordering': ['-cas_vzletu', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Letadlo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imatrikulace', models.CharField(help_text='např. OK-0815', max_length=10, unique=True)),
                ('typ', models.CharField(help_text='např. L-13 Blaník', max_length=60)),
                ('kategorie', models.CharField(choices=[('motor', 'Motorové'), ('tmg', 'TMG'), ('kluzak', 'Kluzák'), ('ul', 'UL')], max_length=10)),
                ('pocet_mist', models.PositiveSmallIntegerField(default=2, verbose_name='počet míst')),
                ('max_doba_min', models.PositiveIntegerField(blank=True, help_text='S plnými nádržemi. U kluzáků prázdné.', null=True, verbose_name='max. doba letu [min]')),
                ('soukrome', models.BooleanField(default=False, help_text='Neexportuje se pro účetnictví.', verbose_name='soukromé')),
                ('vlecne', models.BooleanField(default=False, help_text='Může vlekat kluzáky.', verbose_name='vlečné')),
                ('aktivni', models.BooleanField(default=True, verbose_name='aktivní')),
                ('poradi', models.PositiveSmallIntegerField(default=100, verbose_name='pořadí')),
            ],
            options={
                'verbose_name': 'letadlo',
                'verbose_name_plural': 'letadla',
                'ordering': ['poradi', 'imatrikulace'],
            },
        ),
        migrations.CreateModel(
            name='Letiste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icao', models.CharField(blank=True, max_length=4, null=True, unique=True, verbose_name='ICAO')),
                ('nazev', models.CharField(max_length=80, verbose_name='název')),
                ('domovske', models.BooleanField(default=False, verbose_name='domovské')),
                ('teren', models.BooleanField(default=False, help_text='Přistání do terénu (bez ICAO kódu).', verbose_name='mimo letiště')),
                ('aktivni', models.BooleanField(default=True, verbose_name='aktivní')),
                ('poradi', models.PositiveSmallIntegerField(default=100, verbose_name='pořadí')),
            ],
            options={
                'verbose_name': 'letiště',
                'verbose_name_plural': 'letiště',
                'ordering': ['-domovske', 'poradi', 'nazev'],
            },
        ),
        migrations.CreateModel(
            name='Posadka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funkce', models.CharField(choices=[('pic', 'PIC'), ('zak', 'Žák'), ('prezkouseny', 'Přezkoušený'), ('dozor', 'Dozor (na zemi)'), ('clen', 'Člen posádky')], max_length=12)),
            ],
            options={
                'verbose_name': 'člen posádky',
                'verbose_name_plural': 'posádka',
            },
        ),
        migrations.CreateModel(
            name='Uloha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=20, verbose_name='kód')),
                ('nazev', models.CharField(max_length=120, verbose_name='název')),
                ('osnova', models.CharField(blank=True, help_text='Ke které osnově patří.', max_length=60)),
                ('ucely', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('normalni', 'Normální'), ('vycvik', 'Výcvik'), ('vycvik_solo', 'Výcvik sólo'), ('prezkouseni', 'Přezkoušení'), ('vlek', 'Vlek')], max_length=12), help_text='Pro které účely letu se úloha nabízí.', verbose_name='účely')),
                ('kategorie', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('motor', 'Motorové'), ('tmg', 'TMG'), ('kluzak', 'Kluzák'), ('ul', 'UL')], max_length=10), help_text='Pro které kategorie letadel se úloha nabízí.')),
                ('aktivni', models.BooleanField(default=True, verbose_name='aktivní')),
                ('poradi', models.PositiveSmallIntegerField(default=100, verbose_name='pořadí')),
            ],
            options={
                'verbose_name': 'úloha',
                'verbose_name_plural': 'úlohy',
                'ordering': ['poradi', 'kod'],
            },
        ),
        migrations.CreateModel(
            name='Uzaverka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('den', 'Den'), ('mesic', 'Měsíc')], max_length=5)),
                ('obdobi', models.DateField(help_text='Datum dne, nebo první den měsíce.', verbose_name='období')),
                ('verze', models.PositiveSmallIntegerField(default=1)),
                ('kdy', models.DateTimeField(auto_now_add=True)),
                ('souhrn', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'uzávěrka',
                'verbose_name_plural': 'uzávěrky',
                'ordering': ['-obdobi', '-verze'],
            },
        ),
    ]
