# Generated by Django 6.1.1 on 2026-10-03 20:37

import django.contrib.postgres.constraints
import django.db.models.deletion
import lety.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lety', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='kdo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='let',
            name='platce',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='placene_lety', to=settings.AUTH_USER_MODEL, verbose_name='plátce'),
        ),
        migrations.AddField(
            model_name='let',
            name='vlecny_let',
            field=models.OneToOneField(blank=True, help_text='Jen u kluzáku ve vleku.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vleceny_let', to='lety.let', verbose_name='let vlečného letadla'),
        ),
        migrations.AddField(
            model_name='let',
            name='zalozil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zalozene_lety', to=settings.AUTH_USER_MODEL, verbose_name='založil'),
        ),
        migrations.AddConstraint(
            model_name='letadlo',
            constraint=models.CheckConstraint(condition=models.Q(('pocet_mist__gte', 1), ('pocet_mist__lte', 4)), name='letadlo_pocet_mist'),
        ),
        migrations.AddField(
            model_name='let',
            name='letadlo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lety', to='lety.letadlo'),
        ),
        migrations.AddConstraint(
            model_name='letiste',
            constraint=models.UniqueConstraint(condition=models.Q(('domovske', True)), fields=('domovske',), name='jedno_domovske_letiste'),
        ),
        migrations.AddField(
            model_name='let',
            name='misto_pristani',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='lety.letiste', verbose_name='místo přistání'),
        ),
        migrations.AddField(
            model_name='let',
            name='misto_vzletu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='lety.letiste', verbose_name='místo vzletu'),
        ),
        migrations.AddField(
            model_name='posadka',
            name='let',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posadka', to='lety.let'),
        ),
        migrations.AddField(
            model_name='posadka',
            name='osoba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posadky', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='uloha',
            constraint=models.UniqueConstraint(fields=('osnova', 'kod'), name='uloha_unikatni_kod'),
        ),
        migrations.AddField(
            model_name='let',
            name='uloha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lety', to='lety.uloha', verbose_name='úloha'),
        ),
        migrations.AddField(
            model_name='uzaverka',
            name='uzavrel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='uzavřel'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['objekt', 'objekt_id'], name='lety_auditl_objekt_fff25b_idx'),
        ),
        migrations.AddConstraint(
            model_name='posadka',
            constraint=models.UniqueConstraint(fields=('let', 'osoba'), name='osoba_jednou_na_letu'),
        ),
        migrations.AddConstraint(
            model_name='posadka',
            constraint=models.UniqueConstraint(condition=models.Q(('funkce', 'pic')), fields=('let',), name='jeden_pic_na_letu'),
        ),
        migrations.AddIndex(
            model_name='let',
            index=models.Index(fields=['cas_vzletu'], name='lety_let_cas_vzl_251db2_idx'),
        ),
        migrations.AddConstraint(
            model_name='let',
            constraint=models.CheckConstraint(condition=models.Q(('cas_pristani__isnull', True), models.Q(('cas_pristani__gte', models.F('cas_vzletu')), ('cas_vzletu__isnull', False)), _connector='OR'), name='pristani_po_vzletu', violation_error_message='Přistání nemůže být dřív než vzlet.'),
        ),
        migrations.AddConstraint(
            model_name='let',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('platce__isnull', True), ('plati_aeroklub', True)), models.Q(('platce__isnull', False), ('plati_aeroklub', False)), _connector='OR'), name='prave_jeden_platce', violation_error_message='Let platí buď jedna osoba, nebo aeroklub.'),
        ),
        migrations.AddConstraint(
            model_name='let',
            constraint=models.CheckConstraint(condition=models.Q(('stav', 'zrusen'), ('duvod_zruseni', ''), _connector='OR'), name='duvod_jen_u_zruseneho'),
        ),
        migrations.AddConstraint(
            model_name='let',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('stav', 'zrusen'), _negated=True), models.Q(('duvod_zruseni', ''), _negated=True), _connector='OR'), name='zruseny_ma_duvod', violation_error_message='Zrušený let musí mít důvod.'),
        ),
        migrations.AddConstraint(
            model_name='let',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('cas_vzletu__isnull', False), models.Q(('stav', 'zrusen'), _negated=True)), expressions=[('letadlo', '='), (lety.models.TstzRange('cas_vzletu', 'cas_pristani'), '&&')], name='letadlo_bez_prekryvu', violation_error_message='Letadlo už má v tomto čase jiný let.'),
        ),
        migrations.AddConstraint(
            model_name='uzaverka',
            constraint=models.UniqueConstraint(fields=('typ', 'obdobi', 'verze'), name='uzaverka_verze'),
        ),
    ]
