# Generated by Django 6.1.1 on 2026-10-04 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lety', '0003_auditlog_jen_zapis'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='letadlo',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kategorie', 'kluzak'), _negated=True), models.Q(('max_doba_min__isnull', True), ('vlecne', False)), _connector='OR'), name='kluzak_bez_vleku_a_nadrzi', violation_error_message='Kluzák nemůže být vlečný ani mít maximální dobu letu (nemá nádrže).'),
        ),
    ]
