# Generated by Django 6.1.1 on 2026-10-04 07:28

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


def zadne_ulohy(apps, schema_editor):
    # Pojistka: migrace převod dat neumí, proto nesmí běžet nad existujícími úlohami.
    if apps.get_model("lety", "Uloha").objects.exists():
        raise RuntimeError("V databázi jsou úlohy – migrace 0005 by je neuměla převést.")


class Migration(migrations.Migration):

    dependencies = [
        ('lety', '0004_kluzak_bez_vleku'),
    ]

    operations = [
        migrations.RunPython(zadne_ulohy, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name='uloha',
            options={'ordering': ['osnova', 'poradi', 'kod'], 'verbose_name': 'úloha', 'verbose_name_plural': 'úlohy'},
        ),
        migrations.RemoveField(
            model_name='uloha',
            name='kategorie',
        ),
        migrations.AlterField(
            model_name='uloha',
            name='ucely',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('normalni', 'Normální'), ('vycvik', 'Výcvik'), ('vycvik_solo', 'Výcvik sólo'), ('prezkouseni', 'Přezkoušení'), ('vlek', 'Vlek')], max_length=12), help_text='U kterých účelů letu se úloha nabízí (např. Výcvik a Výcvik sólo).', verbose_name='účely'),
        ),
        migrations.CreateModel(
            name='Osnova',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategorie', models.CharField(choices=[('motor', 'Motorové'), ('tmg', 'TMG'), ('kluzak', 'Kluzák'), ('ul', 'UL')], max_length=10)),
                ('nazev', models.CharField(max_length=80, verbose_name='název')),
                ('aktivni', models.BooleanField(default=True, verbose_name='aktivní')),
                ('poradi', models.PositiveSmallIntegerField(default=100, verbose_name='pořadí')),
            ],
            options={
                'verbose_name': 'osnova',
                'verbose_name_plural': 'osnovy',
                'ordering': ['kategorie', 'poradi', 'nazev'],
                'constraints': [models.UniqueConstraint(fields=('kategorie', 'nazev'), name='osnova_unikatni')],
            },
        ),
        # Osnova byla text, teď je to odkaz na tabulku osnov. Úlohy zatím nikde nejsou,
        # takže sloupec jen nahradíme (bez převodu dat).
        migrations.RemoveConstraint(model_name='uloha', name='uloha_unikatni_kod'),
        migrations.RemoveField(model_name='uloha', name='osnova'),
        migrations.AddField(
            model_name='uloha',
            name='osnova',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ulohy', to='lety.osnova'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='uloha',
            constraint=models.UniqueConstraint(fields=('osnova', 'kod'), name='uloha_unikatni_kod'),
        ),
    ]
