# Generated by Django 6.1.1 on 2026-10-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lety', '0005_osnovy'),
    ]

    operations = [
        migrations.AddField(
            model_name='uzaverka',
            name='znovu_otevreno',
            field=models.DateTimeField(blank=True, help_text='Admin uzávěrku zrušil; období je zase otevřené (verze zůstávají v historii).', null=True, verbose_name='znovu otevřeno'),
        ),
    ]
