# Generated by Django 6.1.1 on 2026-10-04 13:19

import django.contrib.postgres.fields
import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lety', '0006_uzaverka_znovu_otevreno'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='let',
            name='casy_tg',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), blank=True, default=list, help_text='Zapisuje časoměřič tlačítkem T&G během letu; dopsané lety časy nemají.', verbose_name='časy touch-and-go (UTC)'),
        ),
        migrations.AddField(
            model_name='let',
            name='pocet_pristani',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(cas_pristani__isnull=True, then=models.Value(0)), default=django.db.models.expressions.CombinedExpression(models.F('pocet_tg'), '+', models.Value(1))), output_field=models.IntegerField(), verbose_name='přistání'),
        ),
        migrations.AlterField(
            model_name='uzaverka',
            name='uzavrel',
            field=models.ForeignKey(blank=True, help_text='Prázdné = uzavřeno automaticky po soumraku.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='uzavřel'),
        ),
        migrations.AddConstraint(
            model_name='let',
            constraint=models.CheckConstraint(condition=models.Q(('pocet_tg__gte', models.Func(models.F('casy_tg'), function='cardinality'))), name='casy_tg_do_poctu', violation_error_message='Časů touch-and-go nemůže být víc než jejich počet.'),
        ),
    ]
