# Generated by Django 6.1.1 on 2026-10-04 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lety', '0007_casy_tg_a_pristani'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upozorneni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('druh', models.CharField(choices=[('max_doba', 'Déle než maximální doba letu'), ('soumrak', 'Ve vzduchu po konci soumraku'), ('neukonceny', 'Neukončený let z minulého dne')], max_length=12)),
                ('kdy', models.DateTimeField(auto_now_add=True)),
                ('prijemci', models.JSONField(default=dict, help_text='Kolik e-mailů a push upozornění odešlo komu.', verbose_name='příjemci')),
                ('let', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upozorneni', to='lety.let')),
            ],
            options={
                'verbose_name': 'upozornění',
                'verbose_name_plural': 'upozornění',
                'constraints': [models.UniqueConstraint(fields=('let', 'druh'), name='upozorneni_jednou')],
            },
        ),
    ]
