# Generated by Django 6.1.1 on 2026-10-04 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lety', '0008_upozorneni'),
    ]

    operations = [
        migrations.AddField(
            model_name='letadlo',
            name='nalet_pocatek_min',
            field=models.PositiveIntegerField(default=0, help_text='Celkový nálet letadla k datu níže.', verbose_name='nálet z deníku [min]'),
        ),
        migrations.AddField(
            model_name='letadlo',
            name='starty_pocatek',
            field=models.PositiveIntegerField(default=0, help_text='Celkový počet startů k datu níže.', verbose_name='starty z deníku'),
        ),
        migrations.AddField(
            model_name='letadlo',
            name='stav_k',
            field=models.DateField(blank=True, help_text='Prázdné = počítá se jen z evidence LKKL Log.', null=True, verbose_name='stav deníku ke dni'),
        ),
        migrations.CreateModel(
            name='TerminLetadla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(help_text='např. ARC, 100h prohlídka', max_length=80, verbose_name='název')),
                ('datum', models.DateField(blank=True, null=True, verbose_name='do data')),
                ('pri_naletu_h', models.PositiveIntegerField(blank=True, help_text='Celkový nálet letadla.', null=True, verbose_name='při celkovém náletu [h]')),
                ('poznamka', models.CharField(blank=True, max_length=200, verbose_name='poznámka')),
                ('letadlo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminy', to='lety.letadlo')),
            ],
            options={
                'verbose_name': 'termín letadla',
                'verbose_name_plural': 'termíny letadel',
                'ordering': ['letadlo', 'datum', 'pri_naletu_h'],
                'constraints': [models.CheckConstraint(condition=models.Q(('datum__isnull', False), ('pri_naletu_h__isnull', False), _connector='OR'), name='termin_ma_datum_nebo_nalet', violation_error_message='Zadejte datum nebo nálet.')],
            },
        ),
    ]
