# Generated by Django 6.1.1 on 2026-10-04 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciselniky', '0002_vychozi_hodnoty'),
        ('lety', '0009_terminy_letadel'),
    ]

    operations = [
        migrations.AddField(
            model_name='letadlo',
            name='typ_letadla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='letadla', to='ciselniky.typletadla', verbose_name='typ z číselníku'),
        ),
        migrations.AlterField(
            model_name='letadlo',
            name='typ',
            field=models.CharField(help_text='např. L-13 Blaník (při zadání typu z číselníku se doplní)', max_length=60),
        ),
    ]
