# Generated by Django 6.1.1 on 2026-10-04 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciselniky', '0002_vychozi_hodnoty'),
        ('lety', '0011_typy_z_letadel'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminletadla',
            name='druh',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ciselniky.druhterminu'),
        ),
    ]
