# Generated by Django 6.1.1 on 2026-10-04 20:01

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DruhPrukazu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=80, verbose_name='název')),
                ('kod', models.CharField(blank=True, help_text='Hodnota, se kterou počítají pravidla aplikace. Nemazat.', max_length=30, null=True, verbose_name='systémový kód')),
                ('aktivni', models.BooleanField(default=True, verbose_name='aktivní')),
                ('poradi', models.PositiveSmallIntegerField(default=100, verbose_name='pořadí')),
                ('skupina', models.CharField(choices=[('pilotni', 'Pilotní průkaz'), ('instruktor', 'Instruktor'), ('examinator', 'Examinátor'), ('medical', 'Medical'), ('radio', 'Radiofonní průkaz'), ('jazyk', 'Jazyk')], max_length=12)),
                ('kategorie', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('motor', 'Motorové'), ('tmg', 'TMG'), ('kluzak', 'Kluzák'), ('ul', 'UL')], max_length=10), blank=True, default=list, verbose_name='kategorie letadel')),
            ],
            options={
                'verbose_name': 'druh průkazu',
                'verbose_name_plural': 'druhy průkazů',
                'ordering': ['poradi', 'nazev'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('nazev',), name='druh_prukazu_unikatni'), models.UniqueConstraint(fields=('kod',), name='druh_prukazu_kod')],
            },
        ),
        migrations.CreateModel(
            name='DruhTerminu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=80, verbose_name='název')),
                ('kod', models.CharField(blank=True, help_text='Hodnota, se kterou počítají pravidla aplikace. Nemazat.', max_length=30, null=True, verbose_name='systémový kód')),
                ('aktivni', models.BooleanField(default=True, verbose_name='aktivní')),
                ('poradi', models.PositiveSmallIntegerField(default=100, verbose_name='pořadí')),
            ],
            options={
                'verbose_name': 'druh termínu letadla',
                'verbose_name_plural': 'druhy termínů letadel',
                'ordering': ['poradi', 'nazev'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('nazev',), name='druh_terminu_unikatni')],
            },
        ),
        migrations.CreateModel(
            name='ProvozniOpravneni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=80, verbose_name='název')),
                ('kod', models.CharField(blank=True, help_text='Hodnota, se kterou počítají pravidla aplikace. Nemazat.', max_length=30, null=True, verbose_name='systémový kód')),
                ('aktivni', models.BooleanField(default=True, verbose_name='aktivní')),
                ('poradi', models.PositiveSmallIntegerField(default=100, verbose_name='pořadí')),
            ],
            options={
                'verbose_name': 'provozní oprávnění',
                'verbose_name_plural': 'provozní oprávnění',
                'ordering': ['poradi', 'nazev'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('nazev',), name='provozni_unikatni')],
            },
        ),
        migrations.CreateModel(
            name='TypLetadla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=80, verbose_name='název')),
                ('kod', models.CharField(blank=True, help_text='Hodnota, se kterou počítají pravidla aplikace. Nemazat.', max_length=30, null=True, verbose_name='systémový kód')),
                ('aktivni', models.BooleanField(default=True, verbose_name='aktivní')),
                ('poradi', models.PositiveSmallIntegerField(default=100, verbose_name='pořadí')),
                ('kategorie', models.CharField(choices=[('motor', 'Motorové'), ('tmg', 'TMG'), ('kluzak', 'Kluzák'), ('ul', 'UL')], max_length=10)),
            ],
            options={
                'verbose_name': 'typ letadla',
                'verbose_name_plural': 'typy letadel',
                'ordering': ['poradi', 'nazev'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('nazev',), name='typ_letadla_unikatni')],
            },
        ),
        migrations.CreateModel(
            name='KvalifikacePrukazu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=80, verbose_name='název')),
                ('kod', models.CharField(blank=True, help_text='Hodnota, se kterou počítají pravidla aplikace. Nemazat.', max_length=30, null=True, verbose_name='systémový kód')),
                ('aktivni', models.BooleanField(default=True, verbose_name='aktivní')),
                ('poradi', models.PositiveSmallIntegerField(default=100, verbose_name='pořadí')),
                ('ma_platnost', models.BooleanField(default=False, help_text='Na kartě se u ní zadává datum.', verbose_name='má datum platnosti')),
                ('kategorie', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('motor', 'Motorové'), ('tmg', 'TMG'), ('kluzak', 'Kluzák'), ('ul', 'UL')], max_length=10), blank=True, default=list, verbose_name='kategorie letadel')),
                ('druh', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kvalifikace', to='ciselniky.druhprukazu')),
            ],
            options={
                'verbose_name': 'kvalifikace průkazu',
                'verbose_name_plural': 'kvalifikace průkazů',
                'ordering': ['poradi', 'nazev'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('druh', 'nazev'), name='kvalifikace_unikatni'), models.UniqueConstraint(fields=('druh', 'kod'), name='kvalifikace_kod')],
            },
        ),
    ]
