# Generated by Django 6.1.1 on 2026-10-03 20:37

import django.db.models.deletion
import osoby.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Osoba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('jmeno', models.CharField(max_length=60, verbose_name='jméno')),
                ('prijmeni', models.CharField(max_length=60, verbose_name='příjmení')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='e-mail')),
                ('role_casomeric', models.BooleanField(default=False, help_text='Smí zakládat a opravovat lety všech, uzavírat den.', verbose_name='časoměřič / věž')),
                ('role_ucetni', models.BooleanField(default=False, help_text='Opravuje lety, uzavírá měsíc, exportuje.', verbose_name='účetní')),
                ('externi', models.BooleanField(default=False, help_text='Osoba mimo klub (např. examinátor): jen jméno, bez přihlášení a notifikací.', verbose_name='externí')),
                ('is_active', models.BooleanField(default=True, help_text='Neaktivní osoba se nenabízí ve výběrech a nemůže se přihlásit.', verbose_name='aktivní')),
                ('is_staff', models.BooleanField(default=False, help_text='Přístup do administrace.', verbose_name='admin')),
                ('vytvoreno', models.DateTimeField(auto_now_add=True, verbose_name='vytvořeno')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'osoba',
                'verbose_name_plural': 'osoby',
                'ordering': ['prijmeni', 'jmeno'],
            },
            managers=[
                ('objects', osoby.models.OsobaManager()),
            ],
        ),
        migrations.CreateModel(
            name='Opravneni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategorie', models.CharField(choices=[('motor', 'Motorové'), ('tmg', 'TMG'), ('kluzak', 'Kluzák'), ('ul', 'UL')], max_length=10)),
                ('uroven', models.CharField(choices=[('zak', 'Žák'), ('pilot', 'Pilot'), ('instruktor', 'Instruktor'), ('examinator', 'Examinátor')], max_length=12, verbose_name='úroveň')),
                ('platne_do', models.DateField(blank=True, null=True, verbose_name='platné do')),
                ('osoba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opravneni', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'oprávnění',
                'verbose_name_plural': 'oprávnění',
            },
        ),
        migrations.AddConstraint(
            model_name='osoba',
            constraint=models.CheckConstraint(condition=models.Q(('externi', False), ('email__isnull', True), _connector='OR'), name='externi_bez_emailu', violation_error_message='Externí osoba nemá e-mail ani přihlášení.'),
        ),
        migrations.AddConstraint(
            model_name='opravneni',
            constraint=models.UniqueConstraint(fields=('osoba', 'kategorie', 'uroven'), name='opravneni_unikatni'),
        ),
    ]
