# Generated by Django 6.1.1 on 2026-10-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osoby', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='osoba',
            name='testovaci',
            field=models.BooleanField(default=False, help_text='Účet jen pro zkoušení aplikace. Před spuštěním pro celý klub se smaže.', verbose_name='testovací'),
        ),
    ]
