# Generated by Django 6.1.1 on 2026-10-04 07:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osoby', '0002_osoba_testovaci'),
    ]

    operations = [
        migrations.AddField(
            model_name='osoba',
            name='telefon',
            field=models.CharField(blank=True, help_text='Mezinárodní tvar, např. +420731123456.', max_length=16, validators=[django.core.validators.RegexValidator('^\\+\\d{9,15}$', 'Telefon v mezinárodním tvaru, např. +420731123456.')], verbose_name='mobil'),
        ),
    ]
