# Generated by Django 6.1.1 on 2026-10-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osoby', '0003_osoba_telefon'),
    ]

    operations = [
        migrations.AddField(
            model_name='osoba',
            name='pozvanka_odeslana',
            field=models.DateTimeField(blank=True, null=True, verbose_name='pozvánka odeslána'),
        ),
    ]
