# Generated by Django 6.1.1 on 2026-10-04 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osoby', '0004_pozvanka'),
    ]

    operations = [
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('ppl_a', 'PPL(A)'), ('lapl_a', 'LAPL(A)'), ('spl', 'SPL'), ('ull', 'Pilot ULL (LAA ČR)')], max_length=8)),
                ('cislo', models.CharField(blank=True, max_length=40, verbose_name='číslo průkazu')),
                ('poznamka', models.CharField(blank=True, max_length=200, verbose_name='poznámka')),
                ('zmeneno', models.DateTimeField(auto_now=True, verbose_name='změněno')),
                ('osoba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'licence',
                'verbose_name_plural': 'licence',
                'ordering': ['osoba', 'typ'],
            },
        ),
        migrations.CreateModel(
            name='Kvalifikace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('druh', models.CharField(choices=[('sep', 'SEP (land)'), ('tmg', 'TMG'), ('navijak', 'Naviják / auto'), ('vlek', 'Aerovlek'), ('samostart', 'Samostart'), ('guma', 'Guma (bungee)'), ('ull', 'ULL')], max_length=10)),
                ('platnost_do', models.DateField(blank=True, help_text='U PPL(A) konec platnosti kvalifikace SEP/TMG, u ULL platnost průkazu.', null=True, verbose_name='platnost do')),
                ('licence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kvalifikace', to='osoby.licence')),
            ],
            options={
                'verbose_name': 'kvalifikace',
                'verbose_name_plural': 'kvalifikace',
            },
        ),
        migrations.CreateModel(
            name='Medical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trida', models.CharField(choices=[('1', 'Třída 1'), ('2', 'Třída 2'), ('lapl', 'LAPL')], max_length=4, verbose_name='třída')),
                ('platnost_do', models.DateField(verbose_name='platnost do')),
                ('osoba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicaly', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'medical',
                'verbose_name_plural': 'medicaly',
                'ordering': ['osoba', 'trida'],
            },
        ),
        migrations.AddConstraint(
            model_name='licence',
            constraint=models.UniqueConstraint(fields=('osoba', 'typ'), name='licence_jednou'),
        ),
        migrations.AddConstraint(
            model_name='kvalifikace',
            constraint=models.UniqueConstraint(fields=('licence', 'druh'), name='kvalifikace_jednou'),
        ),
        migrations.AddConstraint(
            model_name='medical',
            constraint=models.UniqueConstraint(fields=('osoba', 'trida'), name='medical_jednou'),
        ),
    ]
