# Generated by Django 6.1.1 on 2026-10-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osoby', '0005_licence_a_medical'),
    ]

    operations = [
        migrations.AddField(
            model_name='osoba',
            name='role_spravce',
            field=models.BooleanField(default=False, help_text='Vidí a upravuje licence a medical všech pilotů a termíny letadel.', verbose_name='správce licencí a letadel'),
        ),
        migrations.AlterField(
            model_name='kvalifikace',
            name='druh',
            field=models.CharField(choices=[('sep', 'SEP (land)'), ('tmg', 'TMG'), ('navijak', 'Naviják / auto'), ('vlek', 'Aerovlek'), ('samostart', 'Samostart'), ('guma', 'Guma (bungee)'), ('ull', 'ULL'), ('ofl', 'Omezený (OFL)'), ('vfl', 'Všeobecný (VFL)')], max_length=10),
        ),
        migrations.AlterField(
            model_name='kvalifikace',
            name='platnost_do',
            field=models.DateField(blank=True, help_text='U PPL(A) konec platnosti kvalifikace SEP/TMG, u ULL a radiofonního průkazu platnost průkazu.', null=True, verbose_name='platnost do'),
        ),
        migrations.AlterField(
            model_name='licence',
            name='typ',
            field=models.CharField(choices=[('ppl_a', 'PPL(A)'), ('lapl_a', 'LAPL(A)'), ('spl', 'SPL'), ('ull', 'Pilot ULL (LAA ČR)'), ('radio', 'Radiotelefonista (ČTÚ)')], max_length=8),
        ),
    ]
