# Generated by Django 6.1.1 on 2026-10-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osoby', '0006_role_spravce_radio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kvalifikace',
            name='druh',
            field=models.CharField(choices=[('sep', 'SEP (land)'), ('tmg', 'TMG'), ('navijak', 'Naviják / auto'), ('vlek', 'Aerovlek'), ('samostart', 'Samostart'), ('guma', 'Guma (bungee)'), ('ull', 'ULL'), ('ofl', 'Omezený (OFL)'), ('vfl', 'Všeobecný (VFL)'), ('en_4', 'Angličtina – úroveň 4'), ('en_5', 'Angličtina – úroveň 5'), ('en_6', 'Angličtina – úroveň 6'), ('cs_4', 'Čeština – úroveň 4'), ('cs_5', 'Čeština – úroveň 5'), ('cs_6', 'Čeština – úroveň 6')], max_length=10),
        ),
        migrations.AlterField(
            model_name='licence',
            name='typ',
            field=models.CharField(choices=[('ppl_a', 'PPL(A)'), ('lapl_a', 'LAPL(A)'), ('spl', 'SPL'), ('ull', 'Pilot ULL (LAA ČR)'), ('radio', 'Radiotelefonista (ČTÚ)'), ('jazyk', 'Jazyková způsobilost')], max_length=8),
        ),
    ]
