# Generated by Django 6.1.1 on 2026-10-04 17:52

from django.db import migrations, models


def bez_cestiny(apps, schema_editor):
    """Čeština se už neeviduje (licence na češtinu neexistuje); prázdné záznamy pryč."""
    Kvalifikace = apps.get_model("osoby", "Kvalifikace")
    Licence = apps.get_model("osoby", "Licence")
    Kvalifikace.objects.filter(druh__in=["cs_4", "cs_5", "cs_6"]).delete()
    Licence.objects.filter(typ="jazyk", kvalifikace__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('osoby', '0007_jazykova_zpusobilost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kvalifikace',
            name='druh',
            field=models.CharField(choices=[('sep', 'SEP (land)'), ('tmg', 'TMG'), ('navijak', 'Naviják / auto'), ('vlek', 'Aerovlek'), ('samostart', 'Samostart'), ('guma', 'Guma (bungee)'), ('ull', 'ULL'), ('ofl', 'Omezený (OFL)'), ('vfl', 'Všeobecný (VFL)'), ('en_4', 'ICAO 4'), ('en_5', 'ICAO 5'), ('en_6', 'ICAO 6')], max_length=10),
        ),
        migrations.AlterField(
            model_name='licence',
            name='typ',
            field=models.CharField(choices=[('ppl_a', 'PPL(A)'), ('lapl_a', 'LAPL(A)'), ('spl', 'SPL'), ('ull', 'Pilot ULL (LAA ČR)'), ('radio', 'Radiofonní průkaz (ČTÚ)'), ('jazyk', 'Angličtina (ICAO)')], max_length=8),
        ),
        migrations.RunPython(bez_cestiny, migrations.RunPython.noop),
    ]
