# Generated by Django 6.1.1 on 2026-10-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osoby', '0008_anglictina_icao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opravneni',
            name='uroven',
            field=models.CharField(choices=[('zak', 'Žák'), ('pilot', 'Pilot'), ('instruktor', 'Instruktor'), ('examinator', 'Examinátor'), ('vlekar', 'Vlekař')], max_length=12, verbose_name='úroveň'),
        ),
    ]
