# Generated by Django 6.1.1 on 2026-10-04 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciselniky', '0002_vychozi_hodnoty'),
        ('osoby', '0009_vlekar'),
    ]

    operations = [
        migrations.AddField(
            model_name='osoba',
            name='provozni_opravneni',
            field=models.ManyToManyField(blank=True, related_name='+', to='ciselniky.provozniopravneni', verbose_name='provozní oprávnění'),
        ),
        migrations.CreateModel(
            name='PrukazOsoby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cislo', models.CharField(blank=True, max_length=40, verbose_name='číslo průkazu')),
                ('poznamka', models.CharField(blank=True, max_length=200, verbose_name='poznámka')),
                ('zmeneno', models.DateTimeField(auto_now=True, verbose_name='změněno')),
                ('druh', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ciselniky.druhprukazu', verbose_name='druh')),
                ('osoba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prukazy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'průkaz osoby',
                'verbose_name_plural': 'průkazy osob',
            },
        ),
        migrations.CreateModel(
            name='KvalifikaceOsoby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platnost_do', models.DateField(blank=True, null=True, verbose_name='platnost do')),
                ('kvalifikace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ciselniky.kvalifikaceprukazu')),
                ('prukaz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kvalifikace', to='osoby.prukazosoby')),
            ],
            options={
                'verbose_name': 'kvalifikace osoby',
                'verbose_name_plural': 'kvalifikace osob',
            },
        ),
        migrations.CreateModel(
            name='Vycvik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zahajen', models.DateField(blank=True, null=True, verbose_name='zahájen')),
                ('solo_povoleno', models.DateField(blank=True, null=True, verbose_name='první sólo povoleno')),
                ('ukoncen', models.DateField(blank=True, null=True, verbose_name='ukončen')),
                ('poznamka', models.CharField(blank=True, max_length=200, verbose_name='poznámka')),
                ('druh', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ciselniky.druhprukazu', verbose_name='výcvik na')),
                ('osoba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vycviky', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'výcvik',
                'verbose_name_plural': 'výcviky',
                'ordering': ['-zahajen'],
            },
        ),
        migrations.CreateModel(
            name='Preskoleni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(blank=True, null=True, verbose_name='přeškolen dne')),
                ('osoba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preskoleni', to=settings.AUTH_USER_MODEL)),
                ('typ', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ciselniky.typletadla', verbose_name='typ')),
            ],
            options={
                'verbose_name': 'přeškolení na typ',
                'verbose_name_plural': 'přeškolení na typy',
                'constraints': [models.UniqueConstraint(fields=('osoba', 'typ'), name='preskoleni_jednou')],
            },
        ),
        migrations.AddConstraint(
            model_name='prukazosoby',
            constraint=models.UniqueConstraint(fields=('osoba', 'druh'), name='prukaz_osoby_jednou'),
        ),
        migrations.AddConstraint(
            model_name='kvalifikaceosoby',
            constraint=models.UniqueConstraint(fields=('prukaz', 'kvalifikace'), name='kvalifikace_osoby_jednou'),
        ),
    ]
