# Generated by Django 6.1.1 on 2026-10-04 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osoby', '0011_prevod_dokladu'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='kvalifikace',
            name='kvalifikace_jednou',
        ),
        migrations.RemoveConstraint(
            model_name='licence',
            name='licence_jednou',
        ),
        migrations.RemoveConstraint(
            model_name='medical',
            name='medical_jednou',
        ),
        migrations.RemoveConstraint(
            model_name='opravneni',
            name='opravneni_unikatni',
        ),
        migrations.RemoveField(
            model_name='licence',
            name='osoba',
        ),
        migrations.RemoveField(
            model_name='medical',
            name='osoba',
        ),
        migrations.RemoveField(
            model_name='opravneni',
            name='osoba',
        ),
        migrations.DeleteModel(
            name='Kvalifikace',
        ),
        migrations.DeleteModel(
            name='Licence',
        ),
        migrations.DeleteModel(
            name='Medical',
        ),
        migrations.DeleteModel(
            name='Opravneni',
        ),
    ]
