# Generated by Django 6.1.1 on 2026-10-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nastaveni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_rezim', models.CharField(choices=[('vypnuto', 'Vypnuto – nic se neodesílá'), ('povolene', 'Jen povolené adresy'), ('vse', 'Všem')], default='vypnuto', help_text='Do spuštění pro celý klub nechte „Jen povolené adresy“ nebo „Vypnuto“.', max_length=10, verbose_name='režim odesílání e-mailů')),
                ('povolene_adresy', models.TextField(blank=True, help_text='Jedna adresa na řádek. Lze použít hvězdičku, např. tomas.mandlik+*@gmail.com povolí všechny adresy s přídavkem.', verbose_name='povolené adresy')),
                ('testovaci_provoz', models.BooleanField(default=True, help_text='V záhlaví aplikace se zobrazí pruh „TESTOVACÍ PROVOZ“.', verbose_name='testovací provoz')),
            ],
            options={
                'verbose_name': 'nastavení',
                'verbose_name_plural': 'nastavení',
            },
        ),
    ]
