# Generated by Django 6.1.1 on 2026-10-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provoz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nastaveni',
            name='automaticka_uzaverka',
            field=models.BooleanField(default=True, help_text='Den se uzavře sám, když po soumraku nic neletí ani není připravené. Piloti pak už do dne nic nedopíší – zapíše to časoměřič nebo účetní.', verbose_name='automatická denní uzávěrka'),
        ),
        migrations.AddField(
            model_name='nastaveni',
            name='uzaverka_po_soumraku_min',
            field=models.PositiveSmallIntegerField(default=60, help_text='Kolik minut po konci občanského soumraku se den uzavře.', verbose_name='automatická uzávěrka po konci soumraku [min]'),
        ),
    ]
