# Generated by Django 6.1.1 on 2026-10-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provoz', '0002_automaticka_uzaverka'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nastaveni',
            name='uzaverka_po_soumraku_min',
        ),
        migrations.AlterField(
            model_name='nastaveni',
            name='automaticka_uzaverka',
            field=models.BooleanField(default=True, help_text='Každý den v 5:00 se uzavře předchozí den, pokud v něm nic neletí ani není připravené. Piloti pak už do dne nic nedopíší – zapíše to časoměřič nebo účetní.', verbose_name='automatická denní uzávěrka'),
        ),
    ]
