# Generated by Django 6.1.1 on 2026-10-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provoz', '0003_bez_odkladu_uzaverky'),
    ]

    operations = [
        migrations.AddField(
            model_name='nastaveni',
            name='displej_klic',
            field=models.CharField(blank=True, help_text='Tajná část odkazu na displej bez přihlášení. Prázdné = displej vypnutý.', max_length=64, verbose_name='klíč velkého displeje'),
        ),
    ]
