# Generated by Django 6.1.1 on 2026-10-04 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provoz', '0004_displej_klic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushOdber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=1000, unique=True, verbose_name='adresa push služby')),
                ('p256dh', models.CharField(max_length=200)),
                ('auth', models.CharField(max_length=100)),
                ('zarizeni', models.CharField(blank=True, max_length=200, verbose_name='zařízení')),
                ('vytvoreno', models.DateTimeField(auto_now_add=True, verbose_name='zapnuto')),
                ('osoba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_odbery', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'zařízení pro upozornění',
                'verbose_name_plural': 'zařízení pro upozornění',
            },
        ),
    ]
