# Generated by Django 6.1.1 on 2026-10-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provoz', '0005_push_odber'),
    ]

    operations = [
        migrations.AddField(
            model_name='nastaveni',
            name='hlidat_licence',
            field=models.BooleanField(default=False, help_text='Varování při zakládání letu a přehled rozlétanosti v Můj nálet. Zapněte až budou licence a medical zadané u všech pilotů. Varování nic neblokuje.', verbose_name='hlídat licence, medical a rozlétanost'),
        ),
    ]
