# Generated by Django 6.1.1 on 2026-10-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provoz', '0007_moduly_hlidani'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nastaveni',
            name='hlidat_zpusobilost',
            field=models.BooleanField(default=False, help_text='Licence, kvalifikace, medical a radiofonní průkaz: varování při zakládání letu a přehled v Můj nálet.', verbose_name='hlídat způsobilost pilotů'),
        ),
    ]
